- name: Kew Gardens
  img: images/KewG.jpg
  github: https://github.com/erinmooney/Storybook
  desc: Using XML, Relax-NG, XSLT, and HTML to transcribe the short story <i>Kew Gardens</i> by the English author Virginia Woolf.
  work: Transcribing and marking up the short story by the English author Virginia Woolf in xml. Editing scheme file. Transforming XML to HTML in XSLT.
- name: Weldon's Portfolio Site
  img: images/CS421.png
  github: https://github.com/Yuying-Jin/CS421proj
  desc: This is a portfolio site that showcases projects made for various video games — such as skins, game modes, and levels.
  work: Designing and developing gallery page in ejs and css.
- name: Pie Chart Tutorial
  github: https://github.com/Yuying-Jin/newTutorials/blob/main/yuyingPieChart/pieChart.md
  work: Introducing how to draw pie charts with stroke-dasharray attribute in SVG. Introducing how to label pie charts with polar coordinates in SVG and XSLT.
- name: User-defined Function Tutorial
  github: https://github.com/Yuying-Jin/newTutorials/blob/main/yuyingFunction/xslFunction.md
  work: Introducing how to define functions in XSLT.

